version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install build

python:
  install:
    - method: pip
      path: .
    - method: pip
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py