name: Documentation build (push main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04             # to match .readthedocs
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]      # to match .readthedocs

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and the package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]
        sudo apt update
        sudo apt install --no-install-recommends -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra dvipng cm-super
    - name: Build documentation
      run: |
        cd docs
        make html
